"""Bundled fallback for the admin-owned LLM provider + model catalog.

GENERATED FILE. Do not edit by hand. Regenerate with:
    python apps/jarvis/scripts/gen_bundled_catalog.py

Returned whenever admin is unreachable or the Redis cache is cold, which
includes every CI run. It therefore MIRRORS jarvis_admin_v2's PROVIDER_SEED
exactly rather than trimming it: a shorter list here silently shrinks the
catalog during an outage and breaks the tests that assert full model lists.
NO secrets: ids, labels and display flags only.
"""

from __future__ import annotations

BUNDLED_MODEL_CATALOG: list[dict] = [
	{
		"provider_id": "openai",
		"catalog_id": "openai",
		"label": "OpenAI",
		"subscription_label": "OpenAI",
		"default_base_url": "https://api.openai.com/v1",
		"renderer_id": "openai-codex",
		"auth_profile_id": "openai",
		"supports_api_key": True,
		"supports_subscription": True,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "gpt-5.5",
				"label": "gpt-5.5",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "gpt-5.5",
				"label": "gpt-5.5",
				"tier": "subscription",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "gpt-5.4",
				"label": "gpt-5.4",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
			{
				"model_id": "gpt-5.4",
				"label": "gpt-5.4",
				"tier": "subscription",
				"is_default": False,
				"sort_order": 1,
			},
			{
				"model_id": "gpt-5.4-mini",
				"label": "gpt-5.4-mini",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 2,
			},
			{
				"model_id": "gpt-5.4-mini",
				"label": "gpt-5.4-mini",
				"tier": "subscription",
				"is_default": False,
				"sort_order": 2,
			},
		],
	},
	{
		"provider_id": "anthropic",
		"catalog_id": "anthropic",
		"label": "Anthropic",
		"subscription_label": "Anthropic",
		"default_base_url": "https://api.anthropic.com",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "claude-opus-4-8",
				"label": "claude-opus-4-8",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 0,
			},
			{
				"model_id": "claude-sonnet-4-6",
				"label": "claude-sonnet-4-6",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 1,
			},
			{
				"model_id": "claude-haiku-4-5",
				"label": "claude-haiku-4-5",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 2,
			},
		],
	},
	{
		"provider_id": "google",
		"catalog_id": "gemini",
		"label": "Google Gemini",
		"subscription_label": "Google Gemini",
		"default_base_url": "https://generativelanguage.googleapis.com",
		"renderer_id": "google-gemini-cli",
		"auth_profile_id": "google-gemini-cli",
		"supports_api_key": True,
		"supports_subscription": True,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "gemini-2.5-pro",
				"label": "gemini-2.5-pro",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "gemini-2.5-pro",
				"label": "gemini-2.5-pro",
				"tier": "subscription",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "gemini-2.5-flash",
				"label": "gemini-2.5-flash",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
			{
				"model_id": "gemini-2.5-flash",
				"label": "gemini-2.5-flash",
				"tier": "subscription",
				"is_default": False,
				"sort_order": 1,
			},
			{
				"model_id": "gemini-3.1-flash",
				"label": "gemini-3.1-flash",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 2,
			},
			{
				"model_id": "gemini-3.1-flash-lite",
				"label": "gemini-3.1-flash-lite",
				"tier": "subscription",
				"is_default": False,
				"sort_order": 2,
			},
		],
	},
	{
		"provider_id": "mistral",
		"catalog_id": "mistral",
		"label": "Mistral",
		"subscription_label": "Mistral",
		"default_base_url": "https://api.mistral.ai/v1",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "mistral-large-latest",
				"label": "mistral-large-latest",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "mistral-medium-latest",
				"label": "mistral-medium-latest",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
			{
				"model_id": "mistral-small-latest",
				"label": "mistral-small-latest",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 2,
			},
		],
	},
	{
		"provider_id": "groq",
		"catalog_id": "groq",
		"label": "Groq",
		"subscription_label": "Groq",
		"default_base_url": "https://api.groq.com/openai/v1",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "llama-3.3-70b-versatile",
				"label": "llama-3.3-70b-versatile",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "openai/gpt-oss-120b",
				"label": "openai/gpt-oss-120b",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
			{
				"model_id": "openai/gpt-oss-20b",
				"label": "openai/gpt-oss-20b",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 2,
			},
			{
				"model_id": "llama-3.1-8b-instant",
				"label": "llama-3.1-8b-instant",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 3,
			},
		],
	},
	{
		"provider_id": "together",
		"catalog_id": "together",
		"label": "Together AI",
		"subscription_label": "Together AI",
		"default_base_url": "https://api.together.xyz/v1",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
				"label": "meta-llama/Llama-3.3-70B-Instruct-Turbo",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			}
		],
	},
	{
		"provider_id": "deepseek",
		"catalog_id": "deepseek",
		"label": "DeepSeek",
		"subscription_label": "DeepSeek",
		"default_base_url": "https://api.deepseek.com",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "deepseek-chat",
				"label": "deepseek-chat",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			}
		],
	},
	{
		"provider_id": "moonshot",
		"catalog_id": "moonshot",
		"label": "Moonshot (Kimi)",
		"subscription_label": "Kimi (Moonshot)",
		"default_base_url": "https://api.moonshot.ai/v1",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": True,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "kimi-k2.6",
				"label": "kimi-k2.6",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "kimi-k2.7-code",
				"label": "kimi-k2.7-code",
				"tier": "subscription",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "kimi-k2.6",
				"label": "kimi-k2.6",
				"tier": "subscription",
				"is_default": False,
				"sort_order": 1,
			},
		],
	},
	{
		"provider_id": "openrouter",
		"catalog_id": "openrouter",
		"label": "OpenRouter",
		"subscription_label": "OpenRouter",
		"default_base_url": "https://openrouter.ai/api/v1",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "anthropic/claude-sonnet-4-6",
				"label": "anthropic/claude-sonnet-4-6",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "openai/gpt-5.5",
				"label": "openai/gpt-5.5",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
		],
	},
	{
		"provider_id": "ollama",
		"catalog_id": "ollama",
		"label": "Ollama (local)",
		"subscription_label": "Ollama (local)",
		"default_base_url": "http://host.docker.internal:11434/v1",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": False,
		"is_local": True,
		"models": [
			{
				"model_id": "qwen2.5:3b",
				"label": "qwen2.5:3b",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 0,
			},
			{
				"model_id": "qwen2.5:0.5b",
				"label": "qwen2.5:0.5b",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
			{"model_id": "llama3", "label": "llama3", "tier": "api_key", "is_default": True, "sort_order": 2},
		],
	},
	{
		"provider_id": "vllm",
		"catalog_id": "vllm",
		"label": "vLLM (local)",
		"subscription_label": "vLLM (local)",
		"default_base_url": "",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": True,
		"is_local": True,
		"models": [],
	},
	{
		"provider_id": "xai",
		"catalog_id": "xai",
		"label": "xAI Grok",
		"subscription_label": "xAI Grok",
		"default_base_url": "https://api.x.ai/v1",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": True,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "grok-4.3",
				"label": "grok-4.3",
				"tier": "subscription",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "grok-4.5",
				"label": "grok-4.5",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "grok-4.3",
				"label": "grok-4.3",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
			{
				"model_id": "grok-build-0.1",
				"label": "grok-build-0.1",
				"tier": "subscription",
				"is_default": False,
				"sort_order": 1,
			},
			{
				"model_id": "grok-build-0.1",
				"label": "grok-build-0.1",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 2,
			},
		],
	},
	{
		"provider_id": "openai_compat",
		"catalog_id": "openai_compat",
		"label": "OpenAI-Compatible",
		"subscription_label": "OpenAI-Compatible",
		"default_base_url": "",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": True,
		"is_local": False,
		"models": [
			{
				"model_id": "claude-sonnet-4-6",
				"label": "claude-sonnet-4-6",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 0,
			},
			{
				"model_id": "gpt-4o",
				"label": "gpt-4o",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
			{
				"model_id": "qwen2.5:3b",
				"label": "qwen2.5:3b",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 2,
			},
			{
				"model_id": "llama3",
				"label": "llama3",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 3,
			},
		],
	},
	{
		"provider_id": "zai",
		"catalog_id": "zai",
		"label": "GLM / Z.ai",
		"subscription_label": "GLM / Z.ai",
		"default_base_url": "https://api.z.ai/api/paas/v4",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "glm-4.6",
				"label": "glm-4.6",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "glm-4.7",
				"label": "glm-4.7",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
		],
	},
	{
		"provider_id": "zai_coding",
		"catalog_id": "zai_coding",
		"label": "GLM / Z.ai (Coding Plan)",
		"subscription_label": "GLM / Z.ai (Coding Plan)",
		"default_base_url": "https://api.z.ai/api/coding/paas/v4",
		"renderer_id": "",
		"auth_profile_id": "",
		"supports_api_key": True,
		"supports_subscription": False,
		"needs_base_url": False,
		"is_local": False,
		"models": [
			{
				"model_id": "glm-4.6",
				"label": "glm-4.6",
				"tier": "api_key",
				"is_default": True,
				"sort_order": 0,
			},
			{
				"model_id": "glm-4.7",
				"label": "glm-4.7",
				"tier": "api_key",
				"is_default": False,
				"sort_order": 1,
			},
		],
	},
]
