"""Tests for jarvis.tools.create_doc - second mutating tool.

Uses ``Note`` as the fixture DocType (same reasoning as test_update_doc):
exists on every Frappe site, simple writeable fields, no side effects on
other modules.
"""

from unittest.mock import patch

import frappe
from frappe.tests.utils import FrappeTestCase

from jarvis.exceptions import InvalidArgumentError, PermissionDeniedError
from jarvis.tools.create_doc import create_doc

NOTE_DT = "Note"

# Track docs inserted by tests so tearDown can clean them up. Notes don't
# have a stable test prefix and we want to leave the user's real Notes alone.
_created_in_test: list[str] = []


def _cleanup_created() -> None:
	for name in _created_in_test:
		if frappe.db.exists(NOTE_DT, name):
			frappe.delete_doc(NOTE_DT, name, ignore_permissions=True, force=True)
	_created_in_test.clear()
	frappe.db.commit()


class TestCreateDocValidation(FrappeTestCase):
	"""Argument-shape rejections fire before any DB access."""

	def test_rejects_empty_doctype(self):
		with self.assertRaises(InvalidArgumentError):
			create_doc(doctype="", values={"title": "x"})

	def test_rejects_empty_values_dict(self):
		with self.assertRaises(InvalidArgumentError):
			create_doc(doctype=NOTE_DT, values={})

	def test_rejects_non_dict_values(self):
		with self.assertRaises(InvalidArgumentError):
			create_doc(doctype=NOTE_DT, values="not a dict")

	def test_rejects_protected_system_fields(self):
		"""`owner`, `creation`, `docstatus`, etc. are Frappe-managed.
		`name` is intentionally NOT protected - autoname=prompt DocTypes
		need it."""
		for protected in ["owner", "creation", "modified", "doctype", "docstatus", "parent"]:
			with self.assertRaises(InvalidArgumentError, msg=f"should reject {protected}"):
				create_doc(
					doctype=NOTE_DT,
					values={protected: "tampered", "title": "x"},
				)

	def test_does_not_reject_name(self):
		"""autoname=prompt DocTypes pass `name` in values - don't refuse it
		at the validation layer. (Note doesn't use prompt-autoname, so this
		ends up auto-generated, but the validation must not throw.)"""

		def fake_perm(*a, **kw):
			return True

		def fake_new_doc(dt):
			class _Stub:
				def __init__(self):
					self._values = {}

				def set(self, f, v):
					self._values[f] = v

				def insert(self):
					pass

				def apply_fieldlevel_read_permissions(self):
					pass

				def as_dict(self):
					return {"doctype": dt, "name": "generated", **self._values}

			return _Stub()

		with patch("frappe.has_permission", side_effect=fake_perm):
			with patch("frappe.new_doc", side_effect=fake_new_doc):
				# Should not raise
				result = create_doc(
					doctype=NOTE_DT,
					values={"name": "custom-id", "title": "x"},
				)
				self.assertEqual(result["title"], "x")


class TestCreateDocPermissions(FrappeTestCase):
	"""Calling user must hold CREATE on the target DocType."""

	def test_rejects_when_user_lacks_create_perm(self):
		with patch("frappe.has_permission", return_value=False):
			with self.assertRaises(PermissionDeniedError):
				create_doc(
					doctype=NOTE_DT,
					values={"title": "blocked", "content": "x"},
				)

	def test_checks_create_ptype_at_doctype_level(self):
		"""Unlike update_doc, create has no record yet - perm check is
		DocType-level only (no doc= arg)."""
		called_with = {}

		def fake_perm(doctype, ptype=None, doc=None, **_):
			called_with["doctype"] = doctype
			called_with["ptype"] = ptype
			called_with["doc"] = doc
			return True

		try:
			with patch("frappe.has_permission", side_effect=fake_perm):
				doc = create_doc(
					doctype=NOTE_DT,
					values={"title": "perm-test", "content": "x"},
				)
				_created_in_test.append(doc["name"])
		finally:
			_cleanup_created()

		self.assertEqual(called_with["doctype"], NOTE_DT)
		self.assertEqual(called_with["ptype"], "create")
		# Record-level doc arg is NOT passed - record doesn't exist yet
		self.assertIsNone(called_with["doc"])


class TestCreateDocHappyPath(FrappeTestCase):
	"""End-to-end: real Note insert, real DB row, real perm check
	(Administrator has create on Note)."""

	def tearDown(self):
		_cleanup_created()

	def test_inserts_row_and_returns_full_doc(self):
		result = create_doc(
			doctype=NOTE_DT,
			values={"title": "jarvis-create-test", "content": "hello", "public": 1},
		)
		_created_in_test.append(result["name"])

		# Returned dict has the autogenerated name + supplied fields
		self.assertTrue(result["name"])
		self.assertEqual(result["title"], "jarvis-create-test")
		self.assertEqual(result["content"], "hello")
		self.assertEqual(result["doctype"], NOTE_DT)

		# Row actually exists in the DB
		self.assertTrue(frappe.db.exists(NOTE_DT, result["name"]))

	def test_validate_hooks_still_fire(self):
		"""Required fields enforced by the DocType's validate() must still
		reject - we don't bypass DocType rules."""
		# Note has no required fields by default, so we can't easily test
		# a validate failure without a fixture DocType. Just confirm that
		# doc.insert() is what we call (it's the validate path).
		# This test exists to document the contract; the trust here is in
		# Frappe's own test coverage of insert().
		result = create_doc(
			doctype=NOTE_DT,
			values={"title": "validate-hook-test"},
		)
		_created_in_test.append(result["name"])
		self.assertTrue(result["name"])
