// The GST states/UTs, mirroring India Compliance's STATE_NUMBERS so the checkout
// State picker offers exactly the values the books side (jarvis_billing) can map
// to a place-of-supply code. Order follows the GST state-code sequence.
//
// State is a Select ONLY when Country is India (place of supply is the buyer's
// state); for any other country it is a free-text region and India Compliance
// treats the buyer as Overseas.

export const INDIA = "India";

export const INDIAN_STATES = [
	"Jammu and Kashmir",
	"Himachal Pradesh",
	"Punjab",
	"Chandigarh",
	"Uttarakhand",
	"Haryana",
	"Delhi",
	"Rajasthan",
	"Uttar Pradesh",
	"Bihar",
	"Sikkim",
	"Arunachal Pradesh",
	"Nagaland",
	"Manipur",
	"Mizoram",
	"Tripura",
	"Meghalaya",
	"Assam",
	"West Bengal",
	"Jharkhand",
	"Odisha",
	"Chhattisgarh",
	"Madhya Pradesh",
	"Gujarat",
	"Dadra and Nagar Haveli and Daman and Diu",
	"Maharashtra",
	"Karnataka",
	"Goa",
	"Lakshadweep",
	"Kerala",
	"Tamil Nadu",
	"Puducherry",
	"Andaman and Nicobar Islands",
	"Telangana",
	"Andhra Pradesh",
	"Ladakh",
	"Other Territory",
];

const _STATE_SET = new Set(INDIAN_STATES.map((s) => s.toLowerCase()));

// The full list of Frappe standard Countries. Address.country is a Link to Country, so
// every option must be a real Country name (a literal like "Other" would fail invoice
// creation on the books side). India first (the common case), then the markets Jarvis
// sells into, then the rest alphabetically. The books side only distinguishes India
// (domestic GST) from everything else (Overseas).
export const COUNTRIES = [
	"India",
	"United States",
	"United Kingdom",
	"United Arab Emirates",
	"Singapore",
	"Australia",
	"Canada",
	"Germany",
	"Afghanistan",
	"Albania",
	"Algeria",
	"American Samoa",
	"Andorra",
	"Angola",
	"Anguilla",
	"Antarctica",
	"Antigua and Barbuda",
	"Argentina",
	"Armenia",
	"Aruba",
	"Austria",
	"Azerbaijan",
	"Bahamas",
	"Bahrain",
	"Bangladesh",
	"Barbados",
	"Belarus",
	"Belgium",
	"Belize",
	"Benin",
	"Bermuda",
	"Bhutan",
	"Bolivia, Plurinational State of",
	"Bonaire, Sint Eustatius and Saba",
	"Bosnia and Herzegovina",
	"Botswana",
	"Bouvet Island",
	"Brazil",
	"British Indian Ocean Territory",
	"Brunei Darussalam",
	"Bulgaria",
	"Burkina Faso",
	"Burundi",
	"Cambodia",
	"Cameroon",
	"Cape Verde",
	"Cayman Islands",
	"Central African Republic",
	"Chad",
	"Chile",
	"China",
	"Christmas Island",
	"Cocos (Keeling) Islands",
	"Colombia",
	"Comoros",
	"Congo",
	"Congo, The Democratic Republic of the",
	"Cook Islands",
	"Costa Rica",
	"Croatia",
	"Cuba",
	"Curaçao",
	"Cyprus",
	"Czech Republic",
	"Denmark",
	"Djibouti",
	"Dominica",
	"Dominican Republic",
	"Ecuador",
	"Egypt",
	"El Salvador",
	"Equatorial Guinea",
	"Eritrea",
	"Estonia",
	"Ethiopia",
	"Falkland Islands (Malvinas)",
	"Faroe Islands",
	"Fiji",
	"Finland",
	"France",
	"French Guiana",
	"French Polynesia",
	"French Southern Territories",
	"Gabon",
	"Gambia",
	"Georgia",
	"Ghana",
	"Gibraltar",
	"Greece",
	"Greenland",
	"Grenada",
	"Guadeloupe",
	"Guam",
	"Guatemala",
	"Guernsey",
	"Guinea",
	"Guinea-Bissau",
	"Guyana",
	"Haiti",
	"Heard Island and McDonald Islands",
	"Holy See (Vatican City State)",
	"Honduras",
	"Hong Kong",
	"Hungary",
	"Iceland",
	"Indonesia",
	"Iran",
	"Iraq",
	"Ireland",
	"Isle of Man",
	"Israel",
	"Italy",
	"Ivory Coast",
	"Jamaica",
	"Japan",
	"Jersey",
	"Jordan",
	"Kazakhstan",
	"Kenya",
	"Kiribati",
	"Korea, Democratic Peoples Republic of",
	"Korea, Republic of",
	"Kosovo",
	"Kuwait",
	"Kyrgyzstan",
	"Lao Peoples Democratic Republic",
	"Latvia",
	"Lebanon",
	"Lesotho",
	"Liberia",
	"Libya",
	"Liechtenstein",
	"Lithuania",
	"Luxembourg",
	"Macao",
	"Macedonia",
	"Madagascar",
	"Malawi",
	"Malaysia",
	"Maldives",
	"Mali",
	"Malta",
	"Marshall Islands",
	"Martinique",
	"Mauritania",
	"Mauritius",
	"Mayotte",
	"Mexico",
	"Micronesia, Federated States of",
	"Moldova, Republic of",
	"Monaco",
	"Mongolia",
	"Montenegro",
	"Montserrat",
	"Morocco",
	"Mozambique",
	"Myanmar",
	"Namibia",
	"Nauru",
	"Nepal",
	"Netherlands",
	"New Caledonia",
	"New Zealand",
	"Nicaragua",
	"Niger",
	"Nigeria",
	"Niue",
	"Norfolk Island",
	"Northern Mariana Islands",
	"Norway",
	"Oman",
	"Pakistan",
	"Palau",
	"Palestinian Territory, Occupied",
	"Panama",
	"Papua New Guinea",
	"Paraguay",
	"Peru",
	"Philippines",
	"Pitcairn",
	"Poland",
	"Portugal",
	"Puerto Rico",
	"Qatar",
	"Romania",
	"Russian Federation",
	"Rwanda",
	"Réunion",
	"Saint Barthélemy",
	"Saint Helena, Ascension and Tristan da Cunha",
	"Saint Kitts and Nevis",
	"Saint Lucia",
	"Saint Martin (French part)",
	"Saint Pierre and Miquelon",
	"Saint Vincent and the Grenadines",
	"Samoa",
	"San Marino",
	"Sao Tome and Principe",
	"Saudi Arabia",
	"Senegal",
	"Serbia",
	"Seychelles",
	"Sierra Leone",
	"Sint Maarten (Dutch part)",
	"Slovakia",
	"Slovenia",
	"Solomon Islands",
	"Somalia",
	"South Africa",
	"South Georgia and the South Sandwich Islands",
	"South Sudan",
	"Spain",
	"Sri Lanka",
	"Sudan",
	"Suriname",
	"Svalbard and Jan Mayen",
	"Swaziland",
	"Sweden",
	"Switzerland",
	"Syria",
	"Taiwan",
	"Tajikistan",
	"Tanzania",
	"Thailand",
	"Timor-Leste",
	"Togo",
	"Tokelau",
	"Tonga",
	"Trinidad and Tobago",
	"Tunisia",
	"Turkmenistan",
	"Turks and Caicos Islands",
	"Tuvalu",
	"Türkiye",
	"Uganda",
	"Ukraine",
	"United States Minor Outlying Islands",
	"Uruguay",
	"Uzbekistan",
	"Vanuatu",
	"Venezuela, Bolivarian Republic of",
	"Vietnam",
	"Virgin Islands, British",
	"Virgin Islands, U.S.",
	"Wallis and Futuna",
	"Western Sahara",
	"Yemen",
	"Zambia",
	"Zimbabwe",
	"Åland Islands",
];

// Legacy Frappe Country names that differ from the current country_info.json (this list), so a
// resumed snapshot or an ERP default copied from an older Frappe still resolves to a name the
// Address.country Link accepts. Keys lowercased. Extend as Frappe renames more. (This list holds
// "Türkiye"; an older site holds "Turkey" — most other renames still use their old name here.)
const COUNTRY_ALIASES = {
	turkey: "Türkiye",
};
const _COUNTRY_LC = new Map(COUNTRIES.map((c) => [c.toLowerCase(), c]));

// Resolve a value to its canonical Country name: a known alias, else the case-insensitive match
// from COUNTRIES, else the trimmed value as-is (so isValidCountry rejects a genuine unknown).
export function canonicalCountry(value) {
	const s = (value || "").trim();
	if (!s) return "";
	return COUNTRY_ALIASES[s.toLowerCase()] || _COUNTRY_LC.get(s.toLowerCase()) || s;
}

// Whether a value maps to a real Country (Address.country is a Link, so a value from a resumed
// snapshot / ERP default — which never passed through the select — must be checked, not assumed).
export function isValidCountry(value) {
	const c = canonicalCountry(value);
	return !!c && _COUNTRY_LC.has(c.toLowerCase());
}

export function isIndia(country) {
	return (country || "").trim().toLowerCase() === INDIA.toLowerCase();
}

export function isValidIndianState(state) {
	return _STATE_SET.has((state || "").trim().toLowerCase());
}
